<?php
/**
 * PerplexityApi
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ScrapeBadger\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ScrapeBadger\ApiException;
use ScrapeBadger\Configuration;
use ScrapeBadger\HeaderSelector;
use ScrapeBadger\ObjectSerializer;

/**
 * PerplexityApi Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PerplexityApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'perplexityAskPerplexityAQuestion' => [
            'application/json',
        ],
        'perplexityAskPerplexityAQuestionPost' => [
            'application/json',
        ],
        'perplexityMeasureABrandSVisibilityInAPerplexityAnswer' => [
            'application/json',
        ],
        'perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost' => [
            'application/json',
        ],
        'perplexityPerplexityScraperHealthCheck' => [
            'application/json',
        ],
        'perplexityPerplexityScraperHealthCheckHead' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation perplexityAskPerplexityAQuestion
     *
     * Ask Perplexity a question
     *
     * @param  string $prompt The prompt to send to Perplexity (max 4096 characters). (required)
     * @param  string $country ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestion'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\ScrapeBadger\Model\HTTPValidationError
     */
    public function perplexityAskPerplexityAQuestion($prompt, $country = null, string $contentType = self::contentTypes['perplexityAskPerplexityAQuestion'][0])
    {
        list($response) = $this->perplexityAskPerplexityAQuestionWithHttpInfo($prompt, $country, $contentType);
        return $response;
    }

    /**
     * Operation perplexityAskPerplexityAQuestionWithHttpInfo
     *
     * Ask Perplexity a question
     *
     * @param  string $prompt The prompt to send to Perplexity (max 4096 characters). (required)
     * @param  string $country ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestion'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\ScrapeBadger\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function perplexityAskPerplexityAQuestionWithHttpInfo($prompt, $country = null, string $contentType = self::contentTypes['perplexityAskPerplexityAQuestion'][0])
    {
        $request = $this->perplexityAskPerplexityAQuestionRequest($prompt, $country, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\ScrapeBadger\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ScrapeBadger\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ScrapeBadger\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ScrapeBadger\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation perplexityAskPerplexityAQuestionAsync
     *
     * Ask Perplexity a question
     *
     * @param  string $prompt The prompt to send to Perplexity (max 4096 characters). (required)
     * @param  string $country ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityAskPerplexityAQuestionAsync($prompt, $country = null, string $contentType = self::contentTypes['perplexityAskPerplexityAQuestion'][0])
    {
        return $this->perplexityAskPerplexityAQuestionAsyncWithHttpInfo($prompt, $country, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation perplexityAskPerplexityAQuestionAsyncWithHttpInfo
     *
     * Ask Perplexity a question
     *
     * @param  string $prompt The prompt to send to Perplexity (max 4096 characters). (required)
     * @param  string $country ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityAskPerplexityAQuestionAsyncWithHttpInfo($prompt, $country = null, string $contentType = self::contentTypes['perplexityAskPerplexityAQuestion'][0])
    {
        $returnType = 'mixed';
        $request = $this->perplexityAskPerplexityAQuestionRequest($prompt, $country, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'perplexityAskPerplexityAQuestion'
     *
     * @param  string $prompt The prompt to send to Perplexity (max 4096 characters). (required)
     * @param  string $country ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function perplexityAskPerplexityAQuestionRequest($prompt, $country = null, string $contentType = self::contentTypes['perplexityAskPerplexityAQuestion'][0])
    {

        // verify the required parameter 'prompt' is set
        if ($prompt === null || (is_array($prompt) && count($prompt) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $prompt when calling perplexityAskPerplexityAQuestion'
            );
        }



        $resourcePath = '/v1/perplexity/ask';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $prompt,
            'prompt', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country,
            'country', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation perplexityAskPerplexityAQuestionPost
     *
     * Ask Perplexity a question (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestionPost'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed
     */
    public function perplexityAskPerplexityAQuestionPost(string $contentType = self::contentTypes['perplexityAskPerplexityAQuestionPost'][0])
    {
        list($response) = $this->perplexityAskPerplexityAQuestionPostWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation perplexityAskPerplexityAQuestionPostWithHttpInfo
     *
     * Ask Perplexity a question (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestionPost'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed, HTTP status code, HTTP response headers (array of strings)
     */
    public function perplexityAskPerplexityAQuestionPostWithHttpInfo(string $contentType = self::contentTypes['perplexityAskPerplexityAQuestionPost'][0])
    {
        $request = $this->perplexityAskPerplexityAQuestionPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation perplexityAskPerplexityAQuestionPostAsync
     *
     * Ask Perplexity a question (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityAskPerplexityAQuestionPostAsync(string $contentType = self::contentTypes['perplexityAskPerplexityAQuestionPost'][0])
    {
        return $this->perplexityAskPerplexityAQuestionPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation perplexityAskPerplexityAQuestionPostAsyncWithHttpInfo
     *
     * Ask Perplexity a question (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityAskPerplexityAQuestionPostAsyncWithHttpInfo(string $contentType = self::contentTypes['perplexityAskPerplexityAQuestionPost'][0])
    {
        $returnType = 'mixed';
        $request = $this->perplexityAskPerplexityAQuestionPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'perplexityAskPerplexityAQuestionPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityAskPerplexityAQuestionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function perplexityAskPerplexityAQuestionPostRequest(string $contentType = self::contentTypes['perplexityAskPerplexityAQuestionPost'][0])
    {


        $resourcePath = '/v1/perplexity/ask';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswer
     *
     * Measure a brand&#39;s visibility in a Perplexity answer
     *
     * @param  string $prompt The prompt to ask Perplexity. (required)
     * @param  string $brand Brand name to look for in the answer. (required)
     * @param  string $domain Brand domain, for citation matching. (optional)
     * @param  string $aliases Comma-separated alternative names. (optional)
     * @param  string $competitors Comma-separated competitor names. (optional)
     * @param  string $country ISO-3166 alpha-2 egress country. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\ScrapeBadger\Model\HTTPValidationError
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswer($prompt, $brand, $domain = null, $aliases = null, $competitors = null, $country = null, string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'][0])
    {
        list($response) = $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerWithHttpInfo($prompt, $brand, $domain, $aliases, $competitors, $country, $contentType);
        return $response;
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswerWithHttpInfo
     *
     * Measure a brand&#39;s visibility in a Perplexity answer
     *
     * @param  string $prompt The prompt to ask Perplexity. (required)
     * @param  string $brand Brand name to look for in the answer. (required)
     * @param  string $domain Brand domain, for citation matching. (optional)
     * @param  string $aliases Comma-separated alternative names. (optional)
     * @param  string $competitors Comma-separated competitor names. (optional)
     * @param  string $country ISO-3166 alpha-2 egress country. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\ScrapeBadger\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerWithHttpInfo($prompt, $brand, $domain = null, $aliases = null, $competitors = null, $country = null, string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'][0])
    {
        $request = $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerRequest($prompt, $brand, $domain, $aliases, $competitors, $country, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\ScrapeBadger\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ScrapeBadger\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ScrapeBadger\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ScrapeBadger\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswerAsync
     *
     * Measure a brand&#39;s visibility in a Perplexity answer
     *
     * @param  string $prompt The prompt to ask Perplexity. (required)
     * @param  string $brand Brand name to look for in the answer. (required)
     * @param  string $domain Brand domain, for citation matching. (optional)
     * @param  string $aliases Comma-separated alternative names. (optional)
     * @param  string $competitors Comma-separated competitor names. (optional)
     * @param  string $country ISO-3166 alpha-2 egress country. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerAsync($prompt, $brand, $domain = null, $aliases = null, $competitors = null, $country = null, string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'][0])
    {
        return $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerAsyncWithHttpInfo($prompt, $brand, $domain, $aliases, $competitors, $country, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswerAsyncWithHttpInfo
     *
     * Measure a brand&#39;s visibility in a Perplexity answer
     *
     * @param  string $prompt The prompt to ask Perplexity. (required)
     * @param  string $brand Brand name to look for in the answer. (required)
     * @param  string $domain Brand domain, for citation matching. (optional)
     * @param  string $aliases Comma-separated alternative names. (optional)
     * @param  string $competitors Comma-separated competitor names. (optional)
     * @param  string $country ISO-3166 alpha-2 egress country. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerAsyncWithHttpInfo($prompt, $brand, $domain = null, $aliases = null, $competitors = null, $country = null, string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'][0])
    {
        $returnType = 'mixed';
        $request = $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerRequest($prompt, $brand, $domain, $aliases, $competitors, $country, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'perplexityMeasureABrandSVisibilityInAPerplexityAnswer'
     *
     * @param  string $prompt The prompt to ask Perplexity. (required)
     * @param  string $brand Brand name to look for in the answer. (required)
     * @param  string $domain Brand domain, for citation matching. (optional)
     * @param  string $aliases Comma-separated alternative names. (optional)
     * @param  string $competitors Comma-separated competitor names. (optional)
     * @param  string $country ISO-3166 alpha-2 egress country. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerRequest($prompt, $brand, $domain = null, $aliases = null, $competitors = null, $country = null, string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswer'][0])
    {

        // verify the required parameter 'prompt' is set
        if ($prompt === null || (is_array($prompt) && count($prompt) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $prompt when calling perplexityMeasureABrandSVisibilityInAPerplexityAnswer'
            );
        }

        // verify the required parameter 'brand' is set
        if ($brand === null || (is_array($brand) && count($brand) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $brand when calling perplexityMeasureABrandSVisibilityInAPerplexityAnswer'
            );
        }






        $resourcePath = '/v1/perplexity/brand-visibility';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $prompt,
            'prompt', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $brand,
            'brand', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $domain,
            'domain', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $aliases,
            'aliases', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $competitors,
            'competitors', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country,
            'country', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost
     *
     * Measure a brand&#39;s visibility in a Perplexity answer (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost(string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'][0])
    {
        list($response) = $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostWithHttpInfo
     *
     * Measure a brand&#39;s visibility in a Perplexity answer (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed, HTTP status code, HTTP response headers (array of strings)
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostWithHttpInfo(string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'][0])
    {
        $request = $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostAsync
     *
     * Measure a brand&#39;s visibility in a Perplexity answer (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostAsync(string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'][0])
    {
        return $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostAsyncWithHttpInfo
     *
     * Measure a brand&#39;s visibility in a Perplexity answer (POST)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostAsyncWithHttpInfo(string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'][0])
    {
        $returnType = 'mixed';
        $request = $this->perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostRequest(string $contentType = self::contentTypes['perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost'][0])
    {


        $resourcePath = '/v1/perplexity/brand-visibility';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheck
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheck'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed
     */
    public function perplexityPerplexityScraperHealthCheck(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheck'][0])
    {
        list($response) = $this->perplexityPerplexityScraperHealthCheckWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheckWithHttpInfo
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheck'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed, HTTP status code, HTTP response headers (array of strings)
     */
    public function perplexityPerplexityScraperHealthCheckWithHttpInfo(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheck'][0])
    {
        $request = $this->perplexityPerplexityScraperHealthCheckRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheckAsync
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheck'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityPerplexityScraperHealthCheckAsync(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheck'][0])
    {
        return $this->perplexityPerplexityScraperHealthCheckAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheckAsyncWithHttpInfo
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheck'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityPerplexityScraperHealthCheckAsyncWithHttpInfo(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheck'][0])
    {
        $returnType = 'mixed';
        $request = $this->perplexityPerplexityScraperHealthCheckRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'perplexityPerplexityScraperHealthCheck'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheck'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function perplexityPerplexityScraperHealthCheckRequest(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheck'][0])
    {


        $resourcePath = '/v1/perplexity/health';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheckHead
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheckHead'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed
     */
    public function perplexityPerplexityScraperHealthCheckHead(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheckHead'][0])
    {
        list($response) = $this->perplexityPerplexityScraperHealthCheckHeadWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheckHeadWithHttpInfo
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheckHead'] to see the possible values for this operation
     *
     * @throws \ScrapeBadger\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed, HTTP status code, HTTP response headers (array of strings)
     */
    public function perplexityPerplexityScraperHealthCheckHeadWithHttpInfo(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheckHead'][0])
    {
        $request = $this->perplexityPerplexityScraperHealthCheckHeadRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheckHeadAsync
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheckHead'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityPerplexityScraperHealthCheckHeadAsync(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheckHead'][0])
    {
        return $this->perplexityPerplexityScraperHealthCheckHeadAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation perplexityPerplexityScraperHealthCheckHeadAsyncWithHttpInfo
     *
     * Perplexity scraper health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheckHead'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function perplexityPerplexityScraperHealthCheckHeadAsyncWithHttpInfo(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheckHead'][0])
    {
        $returnType = 'mixed';
        $request = $this->perplexityPerplexityScraperHealthCheckHeadRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'perplexityPerplexityScraperHealthCheckHead'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['perplexityPerplexityScraperHealthCheckHead'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function perplexityPerplexityScraperHealthCheckHeadRequest(string $contentType = self::contentTypes['perplexityPerplexityScraperHealthCheckHead'][0])
    {


        $resourcePath = '/v1/perplexity/health';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'HEAD',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
