<?php
/**
 * SubscriptionInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ScrapeBadger\Model;

use \ArrayAccess;
use \ScrapeBadger\ObjectSerializer;

/**
 * SubscriptionInfo Class Doc Comment
 *
 * @category Class
 * @description Active subscription details (null when PAYG-only).
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SubscriptionInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SubscriptionInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'plan_code' => 'string',
        'plan_title' => 'string',
        'billing_cadence' => 'string',
        'status' => 'string',
        'current_period_start' => '\DateTime',
        'current_period_end' => '\DateTime',
        'cancel_at_period_end' => 'bool',
        'cancel_effective_at' => '\DateTime',
        'monthly_credits' => 'int',
        'pending_plan_code' => 'string',
        'pending_plan_title' => 'string',
        'pending_change_effective_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'plan_code' => null,
        'plan_title' => null,
        'billing_cadence' => null,
        'status' => null,
        'current_period_start' => 'date-time',
        'current_period_end' => 'date-time',
        'cancel_at_period_end' => null,
        'cancel_effective_at' => 'date-time',
        'monthly_credits' => null,
        'pending_plan_code' => null,
        'pending_plan_title' => null,
        'pending_change_effective_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'plan_code' => false,
        'plan_title' => false,
        'billing_cadence' => false,
        'status' => false,
        'current_period_start' => true,
        'current_period_end' => true,
        'cancel_at_period_end' => false,
        'cancel_effective_at' => true,
        'monthly_credits' => false,
        'pending_plan_code' => true,
        'pending_plan_title' => true,
        'pending_change_effective_at' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'plan_code' => 'plan_code',
        'plan_title' => 'plan_title',
        'billing_cadence' => 'billing_cadence',
        'status' => 'status',
        'current_period_start' => 'current_period_start',
        'current_period_end' => 'current_period_end',
        'cancel_at_period_end' => 'cancel_at_period_end',
        'cancel_effective_at' => 'cancel_effective_at',
        'monthly_credits' => 'monthly_credits',
        'pending_plan_code' => 'pending_plan_code',
        'pending_plan_title' => 'pending_plan_title',
        'pending_change_effective_at' => 'pending_change_effective_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'plan_code' => 'setPlanCode',
        'plan_title' => 'setPlanTitle',
        'billing_cadence' => 'setBillingCadence',
        'status' => 'setStatus',
        'current_period_start' => 'setCurrentPeriodStart',
        'current_period_end' => 'setCurrentPeriodEnd',
        'cancel_at_period_end' => 'setCancelAtPeriodEnd',
        'cancel_effective_at' => 'setCancelEffectiveAt',
        'monthly_credits' => 'setMonthlyCredits',
        'pending_plan_code' => 'setPendingPlanCode',
        'pending_plan_title' => 'setPendingPlanTitle',
        'pending_change_effective_at' => 'setPendingChangeEffectiveAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'plan_code' => 'getPlanCode',
        'plan_title' => 'getPlanTitle',
        'billing_cadence' => 'getBillingCadence',
        'status' => 'getStatus',
        'current_period_start' => 'getCurrentPeriodStart',
        'current_period_end' => 'getCurrentPeriodEnd',
        'cancel_at_period_end' => 'getCancelAtPeriodEnd',
        'cancel_effective_at' => 'getCancelEffectiveAt',
        'monthly_credits' => 'getMonthlyCredits',
        'pending_plan_code' => 'getPendingPlanCode',
        'pending_plan_title' => 'getPendingPlanTitle',
        'pending_change_effective_at' => 'getPendingChangeEffectiveAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('plan_code', $data ?? [], null);
        $this->setIfExists('plan_title', $data ?? [], null);
        $this->setIfExists('billing_cadence', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('current_period_start', $data ?? [], null);
        $this->setIfExists('current_period_end', $data ?? [], null);
        $this->setIfExists('cancel_at_period_end', $data ?? [], false);
        $this->setIfExists('cancel_effective_at', $data ?? [], null);
        $this->setIfExists('monthly_credits', $data ?? [], 0);
        $this->setIfExists('pending_plan_code', $data ?? [], null);
        $this->setIfExists('pending_plan_title', $data ?? [], null);
        $this->setIfExists('pending_change_effective_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['plan_code'] === null) {
            $invalidProperties[] = "'plan_code' can't be null";
        }
        if ($this->container['plan_title'] === null) {
            $invalidProperties[] = "'plan_title' can't be null";
        }
        if ($this->container['billing_cadence'] === null) {
            $invalidProperties[] = "'billing_cadence' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets plan_code
     *
     * @return string
     */
    public function getPlanCode()
    {
        return $this->container['plan_code'];
    }

    /**
     * Sets plan_code
     *
     * @param string $plan_code plan_code
     *
     * @return self
     */
    public function setPlanCode($plan_code)
    {
        if (is_null($plan_code)) {
            throw new \InvalidArgumentException('non-nullable plan_code cannot be null');
        }
        $this->container['plan_code'] = $plan_code;

        return $this;
    }

    /**
     * Gets plan_title
     *
     * @return string
     */
    public function getPlanTitle()
    {
        return $this->container['plan_title'];
    }

    /**
     * Sets plan_title
     *
     * @param string $plan_title plan_title
     *
     * @return self
     */
    public function setPlanTitle($plan_title)
    {
        if (is_null($plan_title)) {
            throw new \InvalidArgumentException('non-nullable plan_title cannot be null');
        }
        $this->container['plan_title'] = $plan_title;

        return $this;
    }

    /**
     * Gets billing_cadence
     *
     * @return string
     */
    public function getBillingCadence()
    {
        return $this->container['billing_cadence'];
    }

    /**
     * Sets billing_cadence
     *
     * @param string $billing_cadence billing_cadence
     *
     * @return self
     */
    public function setBillingCadence($billing_cadence)
    {
        if (is_null($billing_cadence)) {
            throw new \InvalidArgumentException('non-nullable billing_cadence cannot be null');
        }
        $this->container['billing_cadence'] = $billing_cadence;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets current_period_start
     *
     * @return \DateTime|null
     */
    public function getCurrentPeriodStart()
    {
        return $this->container['current_period_start'];
    }

    /**
     * Sets current_period_start
     *
     * @param \DateTime|null $current_period_start current_period_start
     *
     * @return self
     */
    public function setCurrentPeriodStart($current_period_start)
    {
        if (is_null($current_period_start)) {
            array_push($this->openAPINullablesSetToNull, 'current_period_start');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('current_period_start', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['current_period_start'] = $current_period_start;

        return $this;
    }

    /**
     * Gets current_period_end
     *
     * @return \DateTime|null
     */
    public function getCurrentPeriodEnd()
    {
        return $this->container['current_period_end'];
    }

    /**
     * Sets current_period_end
     *
     * @param \DateTime|null $current_period_end current_period_end
     *
     * @return self
     */
    public function setCurrentPeriodEnd($current_period_end)
    {
        if (is_null($current_period_end)) {
            array_push($this->openAPINullablesSetToNull, 'current_period_end');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('current_period_end', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['current_period_end'] = $current_period_end;

        return $this;
    }

    /**
     * Gets cancel_at_period_end
     *
     * @return bool|null
     */
    public function getCancelAtPeriodEnd()
    {
        return $this->container['cancel_at_period_end'];
    }

    /**
     * Sets cancel_at_period_end
     *
     * @param bool|null $cancel_at_period_end cancel_at_period_end
     *
     * @return self
     */
    public function setCancelAtPeriodEnd($cancel_at_period_end)
    {
        if (is_null($cancel_at_period_end)) {
            throw new \InvalidArgumentException('non-nullable cancel_at_period_end cannot be null');
        }
        $this->container['cancel_at_period_end'] = $cancel_at_period_end;

        return $this;
    }

    /**
     * Gets cancel_effective_at
     *
     * @return \DateTime|null
     */
    public function getCancelEffectiveAt()
    {
        return $this->container['cancel_effective_at'];
    }

    /**
     * Sets cancel_effective_at
     *
     * @param \DateTime|null $cancel_effective_at cancel_effective_at
     *
     * @return self
     */
    public function setCancelEffectiveAt($cancel_effective_at)
    {
        if (is_null($cancel_effective_at)) {
            array_push($this->openAPINullablesSetToNull, 'cancel_effective_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cancel_effective_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cancel_effective_at'] = $cancel_effective_at;

        return $this;
    }

    /**
     * Gets monthly_credits
     *
     * @return int|null
     */
    public function getMonthlyCredits()
    {
        return $this->container['monthly_credits'];
    }

    /**
     * Sets monthly_credits
     *
     * @param int|null $monthly_credits monthly_credits
     *
     * @return self
     */
    public function setMonthlyCredits($monthly_credits)
    {
        if (is_null($monthly_credits)) {
            throw new \InvalidArgumentException('non-nullable monthly_credits cannot be null');
        }
        $this->container['monthly_credits'] = $monthly_credits;

        return $this;
    }

    /**
     * Gets pending_plan_code
     *
     * @return string|null
     */
    public function getPendingPlanCode()
    {
        return $this->container['pending_plan_code'];
    }

    /**
     * Sets pending_plan_code
     *
     * @param string|null $pending_plan_code pending_plan_code
     *
     * @return self
     */
    public function setPendingPlanCode($pending_plan_code)
    {
        if (is_null($pending_plan_code)) {
            array_push($this->openAPINullablesSetToNull, 'pending_plan_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pending_plan_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pending_plan_code'] = $pending_plan_code;

        return $this;
    }

    /**
     * Gets pending_plan_title
     *
     * @return string|null
     */
    public function getPendingPlanTitle()
    {
        return $this->container['pending_plan_title'];
    }

    /**
     * Sets pending_plan_title
     *
     * @param string|null $pending_plan_title pending_plan_title
     *
     * @return self
     */
    public function setPendingPlanTitle($pending_plan_title)
    {
        if (is_null($pending_plan_title)) {
            array_push($this->openAPINullablesSetToNull, 'pending_plan_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pending_plan_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pending_plan_title'] = $pending_plan_title;

        return $this;
    }

    /**
     * Gets pending_change_effective_at
     *
     * @return \DateTime|null
     */
    public function getPendingChangeEffectiveAt()
    {
        return $this->container['pending_change_effective_at'];
    }

    /**
     * Sets pending_change_effective_at
     *
     * @param \DateTime|null $pending_change_effective_at pending_change_effective_at
     *
     * @return self
     */
    public function setPendingChangeEffectiveAt($pending_change_effective_at)
    {
        if (is_null($pending_change_effective_at)) {
            array_push($this->openAPINullablesSetToNull, 'pending_change_effective_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pending_change_effective_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pending_change_effective_at'] = $pending_change_effective_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


