<?php
/**
 * VintedItemSummary
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ScrapeBadger\Model;

use \ArrayAccess;
use \ScrapeBadger\ObjectSerializer;

/**
 * VintedItemSummary Class Doc Comment
 *
 * @category Class
 * @description An item as search, image search and wardrobe listings return it.
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VintedItemSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'VintedItemSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'title' => 'string',
        'price' => '\ScrapeBadger\Model\VintedPrice',
        'brand_title' => 'string',
        'display_title' => 'string',
        'display_subtitle' => 'string',
        'size_title' => 'string',
        'status' => 'string',
        'url' => 'string',
        'path' => 'string',
        'is_visible' => 'bool',
        'promoted' => 'bool',
        'favourite_count' => 'int',
        'view_count' => 'int',
        'service_fee' => 'string',
        'total_item_price' => 'string',
        'content_source' => 'string',
        'seller_country_code' => 'string',
        'similarity_score' => 'float',
        'user' => '\ScrapeBadger\Model\VintedUserSummary',
        'photo' => '\ScrapeBadger\Model\VintedPhoto',
        'photos' => '\ScrapeBadger\Model\VintedPhoto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'title' => null,
        'price' => null,
        'brand_title' => null,
        'display_title' => null,
        'display_subtitle' => null,
        'size_title' => null,
        'status' => null,
        'url' => null,
        'path' => null,
        'is_visible' => null,
        'promoted' => null,
        'favourite_count' => null,
        'view_count' => null,
        'service_fee' => null,
        'total_item_price' => null,
        'content_source' => null,
        'seller_country_code' => null,
        'similarity_score' => null,
        'user' => null,
        'photo' => null,
        'photos' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'title' => false,
        'price' => false,
        'brand_title' => true,
        'display_title' => true,
        'display_subtitle' => true,
        'size_title' => true,
        'status' => true,
        'url' => false,
        'path' => true,
        'is_visible' => false,
        'promoted' => false,
        'favourite_count' => false,
        'view_count' => false,
        'service_fee' => true,
        'total_item_price' => true,
        'content_source' => true,
        'seller_country_code' => true,
        'similarity_score' => true,
        'user' => true,
        'photo' => true,
        'photos' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'title' => 'title',
        'price' => 'price',
        'brand_title' => 'brand_title',
        'display_title' => 'display_title',
        'display_subtitle' => 'display_subtitle',
        'size_title' => 'size_title',
        'status' => 'status',
        'url' => 'url',
        'path' => 'path',
        'is_visible' => 'is_visible',
        'promoted' => 'promoted',
        'favourite_count' => 'favourite_count',
        'view_count' => 'view_count',
        'service_fee' => 'service_fee',
        'total_item_price' => 'total_item_price',
        'content_source' => 'content_source',
        'seller_country_code' => 'seller_country_code',
        'similarity_score' => 'similarity_score',
        'user' => 'user',
        'photo' => 'photo',
        'photos' => 'photos'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'title' => 'setTitle',
        'price' => 'setPrice',
        'brand_title' => 'setBrandTitle',
        'display_title' => 'setDisplayTitle',
        'display_subtitle' => 'setDisplaySubtitle',
        'size_title' => 'setSizeTitle',
        'status' => 'setStatus',
        'url' => 'setUrl',
        'path' => 'setPath',
        'is_visible' => 'setIsVisible',
        'promoted' => 'setPromoted',
        'favourite_count' => 'setFavouriteCount',
        'view_count' => 'setViewCount',
        'service_fee' => 'setServiceFee',
        'total_item_price' => 'setTotalItemPrice',
        'content_source' => 'setContentSource',
        'seller_country_code' => 'setSellerCountryCode',
        'similarity_score' => 'setSimilarityScore',
        'user' => 'setUser',
        'photo' => 'setPhoto',
        'photos' => 'setPhotos'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'title' => 'getTitle',
        'price' => 'getPrice',
        'brand_title' => 'getBrandTitle',
        'display_title' => 'getDisplayTitle',
        'display_subtitle' => 'getDisplaySubtitle',
        'size_title' => 'getSizeTitle',
        'status' => 'getStatus',
        'url' => 'getUrl',
        'path' => 'getPath',
        'is_visible' => 'getIsVisible',
        'promoted' => 'getPromoted',
        'favourite_count' => 'getFavouriteCount',
        'view_count' => 'getViewCount',
        'service_fee' => 'getServiceFee',
        'total_item_price' => 'getTotalItemPrice',
        'content_source' => 'getContentSource',
        'seller_country_code' => 'getSellerCountryCode',
        'similarity_score' => 'getSimilarityScore',
        'user' => 'getUser',
        'photo' => 'getPhoto',
        'photos' => 'getPhotos'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('brand_title', $data ?? [], null);
        $this->setIfExists('display_title', $data ?? [], null);
        $this->setIfExists('display_subtitle', $data ?? [], null);
        $this->setIfExists('size_title', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('is_visible', $data ?? [], true);
        $this->setIfExists('promoted', $data ?? [], false);
        $this->setIfExists('favourite_count', $data ?? [], 0);
        $this->setIfExists('view_count', $data ?? [], 0);
        $this->setIfExists('service_fee', $data ?? [], null);
        $this->setIfExists('total_item_price', $data ?? [], null);
        $this->setIfExists('content_source', $data ?? [], null);
        $this->setIfExists('seller_country_code', $data ?? [], null);
        $this->setIfExists('similarity_score', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('photo', $data ?? [], null);
        $this->setIfExists('photos', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \ScrapeBadger\Model\VintedPrice
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \ScrapeBadger\Model\VintedPrice $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets brand_title
     *
     * @return string|null
     */
    public function getBrandTitle()
    {
        return $this->container['brand_title'];
    }

    /**
     * Sets brand_title
     *
     * @param string|null $brand_title brand_title
     *
     * @return self
     */
    public function setBrandTitle($brand_title)
    {
        if (is_null($brand_title)) {
            array_push($this->openAPINullablesSetToNull, 'brand_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('brand_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['brand_title'] = $brand_title;

        return $this;
    }

    /**
     * Gets display_title
     *
     * @return string|null
     */
    public function getDisplayTitle()
    {
        return $this->container['display_title'];
    }

    /**
     * Sets display_title
     *
     * @param string|null $display_title display_title
     *
     * @return self
     */
    public function setDisplayTitle($display_title)
    {
        if (is_null($display_title)) {
            array_push($this->openAPINullablesSetToNull, 'display_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['display_title'] = $display_title;

        return $this;
    }

    /**
     * Gets display_subtitle
     *
     * @return string|null
     */
    public function getDisplaySubtitle()
    {
        return $this->container['display_subtitle'];
    }

    /**
     * Sets display_subtitle
     *
     * @param string|null $display_subtitle display_subtitle
     *
     * @return self
     */
    public function setDisplaySubtitle($display_subtitle)
    {
        if (is_null($display_subtitle)) {
            array_push($this->openAPINullablesSetToNull, 'display_subtitle');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_subtitle', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['display_subtitle'] = $display_subtitle;

        return $this;
    }

    /**
     * Gets size_title
     *
     * @return string|null
     */
    public function getSizeTitle()
    {
        return $this->container['size_title'];
    }

    /**
     * Sets size_title
     *
     * @param string|null $size_title size_title
     *
     * @return self
     */
    public function setSizeTitle($size_title)
    {
        if (is_null($size_title)) {
            array_push($this->openAPINullablesSetToNull, 'size_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('size_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['size_title'] = $size_title;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path path
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            array_push($this->openAPINullablesSetToNull, 'path');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('path', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets is_visible
     *
     * @return bool|null
     */
    public function getIsVisible()
    {
        return $this->container['is_visible'];
    }

    /**
     * Sets is_visible
     *
     * @param bool|null $is_visible is_visible
     *
     * @return self
     */
    public function setIsVisible($is_visible)
    {
        if (is_null($is_visible)) {
            throw new \InvalidArgumentException('non-nullable is_visible cannot be null');
        }
        $this->container['is_visible'] = $is_visible;

        return $this;
    }

    /**
     * Gets promoted
     *
     * @return bool|null
     */
    public function getPromoted()
    {
        return $this->container['promoted'];
    }

    /**
     * Sets promoted
     *
     * @param bool|null $promoted promoted
     *
     * @return self
     */
    public function setPromoted($promoted)
    {
        if (is_null($promoted)) {
            throw new \InvalidArgumentException('non-nullable promoted cannot be null');
        }
        $this->container['promoted'] = $promoted;

        return $this;
    }

    /**
     * Gets favourite_count
     *
     * @return int|null
     */
    public function getFavouriteCount()
    {
        return $this->container['favourite_count'];
    }

    /**
     * Sets favourite_count
     *
     * @param int|null $favourite_count favourite_count
     *
     * @return self
     */
    public function setFavouriteCount($favourite_count)
    {
        if (is_null($favourite_count)) {
            throw new \InvalidArgumentException('non-nullable favourite_count cannot be null');
        }
        $this->container['favourite_count'] = $favourite_count;

        return $this;
    }

    /**
     * Gets view_count
     *
     * @return int|null
     */
    public function getViewCount()
    {
        return $this->container['view_count'];
    }

    /**
     * Sets view_count
     *
     * @param int|null $view_count view_count
     *
     * @return self
     */
    public function setViewCount($view_count)
    {
        if (is_null($view_count)) {
            throw new \InvalidArgumentException('non-nullable view_count cannot be null');
        }
        $this->container['view_count'] = $view_count;

        return $this;
    }

    /**
     * Gets service_fee
     *
     * @return string|null
     */
    public function getServiceFee()
    {
        return $this->container['service_fee'];
    }

    /**
     * Sets service_fee
     *
     * @param string|null $service_fee service_fee
     *
     * @return self
     */
    public function setServiceFee($service_fee)
    {
        if (is_null($service_fee)) {
            array_push($this->openAPINullablesSetToNull, 'service_fee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_fee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_fee'] = $service_fee;

        return $this;
    }

    /**
     * Gets total_item_price
     *
     * @return string|null
     */
    public function getTotalItemPrice()
    {
        return $this->container['total_item_price'];
    }

    /**
     * Sets total_item_price
     *
     * @param string|null $total_item_price total_item_price
     *
     * @return self
     */
    public function setTotalItemPrice($total_item_price)
    {
        if (is_null($total_item_price)) {
            array_push($this->openAPINullablesSetToNull, 'total_item_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_item_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_item_price'] = $total_item_price;

        return $this;
    }

    /**
     * Gets content_source
     *
     * @return string|null
     */
    public function getContentSource()
    {
        return $this->container['content_source'];
    }

    /**
     * Sets content_source
     *
     * @param string|null $content_source content_source
     *
     * @return self
     */
    public function setContentSource($content_source)
    {
        if (is_null($content_source)) {
            array_push($this->openAPINullablesSetToNull, 'content_source');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('content_source', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['content_source'] = $content_source;

        return $this;
    }

    /**
     * Gets seller_country_code
     *
     * @return string|null
     */
    public function getSellerCountryCode()
    {
        return $this->container['seller_country_code'];
    }

    /**
     * Sets seller_country_code
     *
     * @param string|null $seller_country_code seller_country_code
     *
     * @return self
     */
    public function setSellerCountryCode($seller_country_code)
    {
        if (is_null($seller_country_code)) {
            array_push($this->openAPINullablesSetToNull, 'seller_country_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('seller_country_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['seller_country_code'] = $seller_country_code;

        return $this;
    }

    /**
     * Gets similarity_score
     *
     * @return float|null
     */
    public function getSimilarityScore()
    {
        return $this->container['similarity_score'];
    }

    /**
     * Sets similarity_score
     *
     * @param float|null $similarity_score similarity_score
     *
     * @return self
     */
    public function setSimilarityScore($similarity_score)
    {
        if (is_null($similarity_score)) {
            array_push($this->openAPINullablesSetToNull, 'similarity_score');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('similarity_score', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['similarity_score'] = $similarity_score;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \ScrapeBadger\Model\VintedUserSummary|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \ScrapeBadger\Model\VintedUserSummary|null $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            array_push($this->openAPINullablesSetToNull, 'user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets photo
     *
     * @return \ScrapeBadger\Model\VintedPhoto|null
     */
    public function getPhoto()
    {
        return $this->container['photo'];
    }

    /**
     * Sets photo
     *
     * @param \ScrapeBadger\Model\VintedPhoto|null $photo photo
     *
     * @return self
     */
    public function setPhoto($photo)
    {
        if (is_null($photo)) {
            array_push($this->openAPINullablesSetToNull, 'photo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('photo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['photo'] = $photo;

        return $this;
    }

    /**
     * Gets photos
     *
     * @return \ScrapeBadger\Model\VintedPhoto[]|null
     */
    public function getPhotos()
    {
        return $this->container['photos'];
    }

    /**
     * Sets photos
     *
     * @param \ScrapeBadger\Model\VintedPhoto[]|null $photos photos
     *
     * @return self
     */
    public function setPhotos($photos)
    {
        if (is_null($photos)) {
            throw new \InvalidArgumentException('non-nullable photos cannot be null');
        }
        $this->container['photos'] = $photos;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


