<?php
/**
 * VintedImageSearchRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ScrapeBadger\Model;

use \ArrayAccess;
use \ScrapeBadger\ObjectSerializer;

/**
 * VintedImageSearchRequest Class Doc Comment
 *
 * @category Class
 * @description Search by exactly one public image URL or base64-encoded image.
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VintedImageSearchRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'VintedImageSearchRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'image_url' => 'string',
        'image_base64' => 'string',
        'market' => 'string',
        'page' => 'int',
        'per_page' => 'int',
        'price_from' => 'float',
        'price_to' => 'float',
        'brand_ids' => 'string',
        'catalog_ids' => 'string',
        'color_ids' => 'string',
        'size_ids' => 'string',
        'material_ids' => 'string',
        'status_ids' => 'string',
        'time' => 'int',
        'search_session_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'image_url' => null,
        'image_base64' => null,
        'market' => null,
        'page' => null,
        'per_page' => null,
        'price_from' => null,
        'price_to' => null,
        'brand_ids' => null,
        'catalog_ids' => null,
        'color_ids' => null,
        'size_ids' => null,
        'material_ids' => null,
        'status_ids' => null,
        'time' => null,
        'search_session_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'image_url' => true,
        'image_base64' => true,
        'market' => false,
        'page' => false,
        'per_page' => false,
        'price_from' => true,
        'price_to' => true,
        'brand_ids' => true,
        'catalog_ids' => true,
        'color_ids' => true,
        'size_ids' => true,
        'material_ids' => true,
        'status_ids' => true,
        'time' => true,
        'search_session_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'image_url' => 'image_url',
        'image_base64' => 'image_base64',
        'market' => 'market',
        'page' => 'page',
        'per_page' => 'per_page',
        'price_from' => 'price_from',
        'price_to' => 'price_to',
        'brand_ids' => 'brand_ids',
        'catalog_ids' => 'catalog_ids',
        'color_ids' => 'color_ids',
        'size_ids' => 'size_ids',
        'material_ids' => 'material_ids',
        'status_ids' => 'status_ids',
        'time' => 'time',
        'search_session_id' => 'search_session_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'image_url' => 'setImageUrl',
        'image_base64' => 'setImageBase64',
        'market' => 'setMarket',
        'page' => 'setPage',
        'per_page' => 'setPerPage',
        'price_from' => 'setPriceFrom',
        'price_to' => 'setPriceTo',
        'brand_ids' => 'setBrandIds',
        'catalog_ids' => 'setCatalogIds',
        'color_ids' => 'setColorIds',
        'size_ids' => 'setSizeIds',
        'material_ids' => 'setMaterialIds',
        'status_ids' => 'setStatusIds',
        'time' => 'setTime',
        'search_session_id' => 'setSearchSessionId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'image_url' => 'getImageUrl',
        'image_base64' => 'getImageBase64',
        'market' => 'getMarket',
        'page' => 'getPage',
        'per_page' => 'getPerPage',
        'price_from' => 'getPriceFrom',
        'price_to' => 'getPriceTo',
        'brand_ids' => 'getBrandIds',
        'catalog_ids' => 'getCatalogIds',
        'color_ids' => 'getColorIds',
        'size_ids' => 'getSizeIds',
        'material_ids' => 'getMaterialIds',
        'status_ids' => 'getStatusIds',
        'time' => 'getTime',
        'search_session_id' => 'getSearchSessionId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('image_base64', $data ?? [], null);
        $this->setIfExists('market', $data ?? [], 'fr');
        $this->setIfExists('page', $data ?? [], 1);
        $this->setIfExists('per_page', $data ?? [], 20);
        $this->setIfExists('price_from', $data ?? [], null);
        $this->setIfExists('price_to', $data ?? [], null);
        $this->setIfExists('brand_ids', $data ?? [], null);
        $this->setIfExists('catalog_ids', $data ?? [], null);
        $this->setIfExists('color_ids', $data ?? [], null);
        $this->setIfExists('size_ids', $data ?? [], null);
        $this->setIfExists('material_ids', $data ?? [], null);
        $this->setIfExists('status_ids', $data ?? [], null);
        $this->setIfExists('time', $data ?? [], null);
        $this->setIfExists('search_session_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['image_url']) && (mb_strlen($this->container['image_url']) > 4096)) {
            $invalidProperties[] = "invalid value for 'image_url', the character length must be smaller than or equal to 4096.";
        }

        if (!is_null($this->container['image_base64']) && (mb_strlen($this->container['image_base64']) > 7100000)) {
            $invalidProperties[] = "invalid value for 'image_base64', the character length must be smaller than or equal to 7100000.";
        }

        if (!is_null($this->container['page']) && ($this->container['page'] < 1)) {
            $invalidProperties[] = "invalid value for 'page', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['per_page']) && ($this->container['per_page'] > 96)) {
            $invalidProperties[] = "invalid value for 'per_page', must be smaller than or equal to 96.";
        }

        if (!is_null($this->container['per_page']) && ($this->container['per_page'] < 1)) {
            $invalidProperties[] = "invalid value for 'per_page', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['price_from']) && ($this->container['price_from'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'price_from', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['price_to']) && ($this->container['price_to'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'price_to', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['brand_ids']) && (mb_strlen($this->container['brand_ids']) > 1000)) {
            $invalidProperties[] = "invalid value for 'brand_ids', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['brand_ids']) && !preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", $this->container['brand_ids'])) {
            $invalidProperties[] = "invalid value for 'brand_ids', must be conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.";
        }

        if (!is_null($this->container['catalog_ids']) && (mb_strlen($this->container['catalog_ids']) > 1000)) {
            $invalidProperties[] = "invalid value for 'catalog_ids', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['catalog_ids']) && !preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", $this->container['catalog_ids'])) {
            $invalidProperties[] = "invalid value for 'catalog_ids', must be conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.";
        }

        if (!is_null($this->container['color_ids']) && (mb_strlen($this->container['color_ids']) > 1000)) {
            $invalidProperties[] = "invalid value for 'color_ids', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['color_ids']) && !preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", $this->container['color_ids'])) {
            $invalidProperties[] = "invalid value for 'color_ids', must be conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.";
        }

        if (!is_null($this->container['size_ids']) && (mb_strlen($this->container['size_ids']) > 1000)) {
            $invalidProperties[] = "invalid value for 'size_ids', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['size_ids']) && !preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", $this->container['size_ids'])) {
            $invalidProperties[] = "invalid value for 'size_ids', must be conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.";
        }

        if (!is_null($this->container['material_ids']) && (mb_strlen($this->container['material_ids']) > 1000)) {
            $invalidProperties[] = "invalid value for 'material_ids', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['material_ids']) && !preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", $this->container['material_ids'])) {
            $invalidProperties[] = "invalid value for 'material_ids', must be conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.";
        }

        if (!is_null($this->container['status_ids']) && (mb_strlen($this->container['status_ids']) > 1000)) {
            $invalidProperties[] = "invalid value for 'status_ids', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['status_ids']) && !preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", $this->container['status_ids'])) {
            $invalidProperties[] = "invalid value for 'status_ids', must be conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.";
        }

        if (!is_null($this->container['time']) && ($this->container['time'] < 0)) {
            $invalidProperties[] = "invalid value for 'time', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['search_session_id']) && (mb_strlen($this->container['search_session_id']) > 100)) {
            $invalidProperties[] = "invalid value for 'search_session_id', the character length must be smaller than or equal to 100.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            array_push($this->openAPINullablesSetToNull, 'image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($image_url) && (mb_strlen($image_url) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $image_url when calling VintedImageSearchRequest., must be smaller than or equal to 4096.');
        }

        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets image_base64
     *
     * @return string|null
     */
    public function getImageBase64()
    {
        return $this->container['image_base64'];
    }

    /**
     * Sets image_base64
     *
     * @param string|null $image_base64 image_base64
     *
     * @return self
     */
    public function setImageBase64($image_base64)
    {
        if (is_null($image_base64)) {
            array_push($this->openAPINullablesSetToNull, 'image_base64');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_base64', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($image_base64) && (mb_strlen($image_base64) > 7100000)) {
            throw new \InvalidArgumentException('invalid length for $image_base64 when calling VintedImageSearchRequest., must be smaller than or equal to 7100000.');
        }

        $this->container['image_base64'] = $image_base64;

        return $this;
    }

    /**
     * Gets market
     *
     * @return string|null
     */
    public function getMarket()
    {
        return $this->container['market'];
    }

    /**
     * Sets market
     *
     * @param string|null $market Vinted market code; uk aliases gb
     *
     * @return self
     */
    public function setMarket($market)
    {
        if (is_null($market)) {
            throw new \InvalidArgumentException('non-nullable market cannot be null');
        }
        $this->container['market'] = $market;

        return $this;
    }

    /**
     * Gets page
     *
     * @return int|null
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param int|null $page page
     *
     * @return self
     */
    public function setPage($page)
    {
        if (is_null($page)) {
            throw new \InvalidArgumentException('non-nullable page cannot be null');
        }

        if (($page < 1)) {
            throw new \InvalidArgumentException('invalid value for $page when calling VintedImageSearchRequest., must be bigger than or equal to 1.');
        }

        $this->container['page'] = $page;

        return $this;
    }

    /**
     * Gets per_page
     *
     * @return int|null
     */
    public function getPerPage()
    {
        return $this->container['per_page'];
    }

    /**
     * Sets per_page
     *
     * @param int|null $per_page per_page
     *
     * @return self
     */
    public function setPerPage($per_page)
    {
        if (is_null($per_page)) {
            throw new \InvalidArgumentException('non-nullable per_page cannot be null');
        }

        if (($per_page > 96)) {
            throw new \InvalidArgumentException('invalid value for $per_page when calling VintedImageSearchRequest., must be smaller than or equal to 96.');
        }
        if (($per_page < 1)) {
            throw new \InvalidArgumentException('invalid value for $per_page when calling VintedImageSearchRequest., must be bigger than or equal to 1.');
        }

        $this->container['per_page'] = $per_page;

        return $this;
    }

    /**
     * Gets price_from
     *
     * @return float|null
     */
    public function getPriceFrom()
    {
        return $this->container['price_from'];
    }

    /**
     * Sets price_from
     *
     * @param float|null $price_from price_from
     *
     * @return self
     */
    public function setPriceFrom($price_from)
    {
        if (is_null($price_from)) {
            array_push($this->openAPINullablesSetToNull, 'price_from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price_from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($price_from) && ($price_from < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $price_from when calling VintedImageSearchRequest., must be bigger than or equal to 0.0.');
        }

        $this->container['price_from'] = $price_from;

        return $this;
    }

    /**
     * Gets price_to
     *
     * @return float|null
     */
    public function getPriceTo()
    {
        return $this->container['price_to'];
    }

    /**
     * Sets price_to
     *
     * @param float|null $price_to price_to
     *
     * @return self
     */
    public function setPriceTo($price_to)
    {
        if (is_null($price_to)) {
            array_push($this->openAPINullablesSetToNull, 'price_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($price_to) && ($price_to < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $price_to when calling VintedImageSearchRequest., must be bigger than or equal to 0.0.');
        }

        $this->container['price_to'] = $price_to;

        return $this;
    }

    /**
     * Gets brand_ids
     *
     * @return string|null
     */
    public function getBrandIds()
    {
        return $this->container['brand_ids'];
    }

    /**
     * Sets brand_ids
     *
     * @param string|null $brand_ids brand_ids
     *
     * @return self
     */
    public function setBrandIds($brand_ids)
    {
        if (is_null($brand_ids)) {
            array_push($this->openAPINullablesSetToNull, 'brand_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('brand_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($brand_ids) && (mb_strlen($brand_ids) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $brand_ids when calling VintedImageSearchRequest., must be smaller than or equal to 1000.');
        }
        if (!is_null($brand_ids) && (!preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", ObjectSerializer::toString($brand_ids)))) {
            throw new \InvalidArgumentException("invalid value for \$brand_ids when calling VintedImageSearchRequest., must conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.");
        }

        $this->container['brand_ids'] = $brand_ids;

        return $this;
    }

    /**
     * Gets catalog_ids
     *
     * @return string|null
     */
    public function getCatalogIds()
    {
        return $this->container['catalog_ids'];
    }

    /**
     * Sets catalog_ids
     *
     * @param string|null $catalog_ids catalog_ids
     *
     * @return self
     */
    public function setCatalogIds($catalog_ids)
    {
        if (is_null($catalog_ids)) {
            array_push($this->openAPINullablesSetToNull, 'catalog_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('catalog_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($catalog_ids) && (mb_strlen($catalog_ids) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $catalog_ids when calling VintedImageSearchRequest., must be smaller than or equal to 1000.');
        }
        if (!is_null($catalog_ids) && (!preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", ObjectSerializer::toString($catalog_ids)))) {
            throw new \InvalidArgumentException("invalid value for \$catalog_ids when calling VintedImageSearchRequest., must conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.");
        }

        $this->container['catalog_ids'] = $catalog_ids;

        return $this;
    }

    /**
     * Gets color_ids
     *
     * @return string|null
     */
    public function getColorIds()
    {
        return $this->container['color_ids'];
    }

    /**
     * Sets color_ids
     *
     * @param string|null $color_ids color_ids
     *
     * @return self
     */
    public function setColorIds($color_ids)
    {
        if (is_null($color_ids)) {
            array_push($this->openAPINullablesSetToNull, 'color_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($color_ids) && (mb_strlen($color_ids) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $color_ids when calling VintedImageSearchRequest., must be smaller than or equal to 1000.');
        }
        if (!is_null($color_ids) && (!preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", ObjectSerializer::toString($color_ids)))) {
            throw new \InvalidArgumentException("invalid value for \$color_ids when calling VintedImageSearchRequest., must conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.");
        }

        $this->container['color_ids'] = $color_ids;

        return $this;
    }

    /**
     * Gets size_ids
     *
     * @return string|null
     */
    public function getSizeIds()
    {
        return $this->container['size_ids'];
    }

    /**
     * Sets size_ids
     *
     * @param string|null $size_ids size_ids
     *
     * @return self
     */
    public function setSizeIds($size_ids)
    {
        if (is_null($size_ids)) {
            array_push($this->openAPINullablesSetToNull, 'size_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('size_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($size_ids) && (mb_strlen($size_ids) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $size_ids when calling VintedImageSearchRequest., must be smaller than or equal to 1000.');
        }
        if (!is_null($size_ids) && (!preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", ObjectSerializer::toString($size_ids)))) {
            throw new \InvalidArgumentException("invalid value for \$size_ids when calling VintedImageSearchRequest., must conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.");
        }

        $this->container['size_ids'] = $size_ids;

        return $this;
    }

    /**
     * Gets material_ids
     *
     * @return string|null
     */
    public function getMaterialIds()
    {
        return $this->container['material_ids'];
    }

    /**
     * Sets material_ids
     *
     * @param string|null $material_ids material_ids
     *
     * @return self
     */
    public function setMaterialIds($material_ids)
    {
        if (is_null($material_ids)) {
            array_push($this->openAPINullablesSetToNull, 'material_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('material_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($material_ids) && (mb_strlen($material_ids) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $material_ids when calling VintedImageSearchRequest., must be smaller than or equal to 1000.');
        }
        if (!is_null($material_ids) && (!preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", ObjectSerializer::toString($material_ids)))) {
            throw new \InvalidArgumentException("invalid value for \$material_ids when calling VintedImageSearchRequest., must conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.");
        }

        $this->container['material_ids'] = $material_ids;

        return $this;
    }

    /**
     * Gets status_ids
     *
     * @return string|null
     */
    public function getStatusIds()
    {
        return $this->container['status_ids'];
    }

    /**
     * Sets status_ids
     *
     * @param string|null $status_ids status_ids
     *
     * @return self
     */
    public function setStatusIds($status_ids)
    {
        if (is_null($status_ids)) {
            array_push($this->openAPINullablesSetToNull, 'status_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($status_ids) && (mb_strlen($status_ids) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $status_ids when calling VintedImageSearchRequest., must be smaller than or equal to 1000.');
        }
        if (!is_null($status_ids) && (!preg_match("/^[1-9][0-9]*(,[1-9][0-9]*)*$/", ObjectSerializer::toString($status_ids)))) {
            throw new \InvalidArgumentException("invalid value for \$status_ids when calling VintedImageSearchRequest., must conform to the pattern /^[1-9][0-9]*(,[1-9][0-9]*)*$/.");
        }

        $this->container['status_ids'] = $status_ids;

        return $this;
    }

    /**
     * Gets time
     *
     * @return int|null
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param int|null $time time
     *
     * @return self
     */
    public function setTime($time)
    {
        if (is_null($time)) {
            array_push($this->openAPINullablesSetToNull, 'time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($time) && ($time < 0)) {
            throw new \InvalidArgumentException('invalid value for $time when calling VintedImageSearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets search_session_id
     *
     * @return string|null
     */
    public function getSearchSessionId()
    {
        return $this->container['search_session_id'];
    }

    /**
     * Sets search_session_id
     *
     * @param string|null $search_session_id search_session_id
     *
     * @return self
     */
    public function setSearchSessionId($search_session_id)
    {
        if (is_null($search_session_id)) {
            array_push($this->openAPINullablesSetToNull, 'search_session_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('search_session_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($search_session_id) && (mb_strlen($search_session_id) > 100)) {
            throw new \InvalidArgumentException('invalid length for $search_session_id when calling VintedImageSearchRequest., must be smaller than or equal to 100.');
        }

        $this->container['search_session_id'] = $search_session_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


