<?php
/**
 * VintedItemDetail
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ScrapeBadger\Model;

use \ArrayAccess;
use \ScrapeBadger\ObjectSerializer;

/**
 * VintedItemDetail Class Doc Comment
 *
 * @category Class
 * @description A single listing with the fields only the detail endpoint carries.
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VintedItemDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'VintedItemDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'title' => 'string',
        'price' => '\ScrapeBadger\Model\VintedPrice',
        'brand_title' => 'string',
        'display_title' => 'string',
        'display_subtitle' => 'string',
        'size_title' => 'string',
        'status' => 'string',
        'url' => 'string',
        'path' => 'string',
        'is_visible' => 'bool',
        'promoted' => 'bool',
        'favourite_count' => 'int',
        'view_count' => 'int',
        'service_fee' => 'string',
        'total_item_price' => 'string',
        'content_source' => 'string',
        'seller_country_code' => 'string',
        'similarity_score' => 'float',
        'user' => '\ScrapeBadger\Model\VintedUserSummary',
        'photo' => '\ScrapeBadger\Model\VintedPhoto',
        'photos' => '\ScrapeBadger\Model\VintedPhoto[]',
        'description' => 'string',
        'catalog_id' => 'int',
        'color1' => 'string',
        'color2' => 'string',
        'package_size_id' => 'int',
        'is_favourite' => 'bool',
        'can_buy' => 'bool',
        'can_bundle' => 'bool',
        'can_reserve' => 'bool',
        'instant_buy' => 'bool',
        'is_hidden' => 'bool',
        'is_reserved' => 'bool',
        'is_closed' => 'bool',
        'seller' => '\ScrapeBadger\Model\VintedSellerSummary',
        'size_id' => 'int',
        'status_id' => 'int',
        'brand_id' => 'int',
        'category' => 'string[]',
        'upload_date' => 'string',
        'uploaded_at' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'title' => null,
        'price' => null,
        'brand_title' => null,
        'display_title' => null,
        'display_subtitle' => null,
        'size_title' => null,
        'status' => null,
        'url' => null,
        'path' => null,
        'is_visible' => null,
        'promoted' => null,
        'favourite_count' => null,
        'view_count' => null,
        'service_fee' => null,
        'total_item_price' => null,
        'content_source' => null,
        'seller_country_code' => null,
        'similarity_score' => null,
        'user' => null,
        'photo' => null,
        'photos' => null,
        'description' => null,
        'catalog_id' => null,
        'color1' => null,
        'color2' => null,
        'package_size_id' => null,
        'is_favourite' => null,
        'can_buy' => null,
        'can_bundle' => null,
        'can_reserve' => null,
        'instant_buy' => null,
        'is_hidden' => null,
        'is_reserved' => null,
        'is_closed' => null,
        'seller' => null,
        'size_id' => null,
        'status_id' => null,
        'brand_id' => null,
        'category' => null,
        'upload_date' => null,
        'uploaded_at' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'title' => false,
        'price' => false,
        'brand_title' => true,
        'display_title' => true,
        'display_subtitle' => true,
        'size_title' => true,
        'status' => true,
        'url' => false,
        'path' => true,
        'is_visible' => false,
        'promoted' => false,
        'favourite_count' => false,
        'view_count' => false,
        'service_fee' => true,
        'total_item_price' => true,
        'content_source' => true,
        'seller_country_code' => true,
        'similarity_score' => true,
        'user' => true,
        'photo' => true,
        'photos' => false,
        'description' => true,
        'catalog_id' => true,
        'color1' => true,
        'color2' => true,
        'package_size_id' => true,
        'is_favourite' => false,
        'can_buy' => false,
        'can_bundle' => false,
        'can_reserve' => false,
        'instant_buy' => false,
        'is_hidden' => false,
        'is_reserved' => false,
        'is_closed' => false,
        'seller' => true,
        'size_id' => true,
        'status_id' => true,
        'brand_id' => true,
        'category' => false,
        'upload_date' => true,
        'uploaded_at' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'title' => 'title',
        'price' => 'price',
        'brand_title' => 'brand_title',
        'display_title' => 'display_title',
        'display_subtitle' => 'display_subtitle',
        'size_title' => 'size_title',
        'status' => 'status',
        'url' => 'url',
        'path' => 'path',
        'is_visible' => 'is_visible',
        'promoted' => 'promoted',
        'favourite_count' => 'favourite_count',
        'view_count' => 'view_count',
        'service_fee' => 'service_fee',
        'total_item_price' => 'total_item_price',
        'content_source' => 'content_source',
        'seller_country_code' => 'seller_country_code',
        'similarity_score' => 'similarity_score',
        'user' => 'user',
        'photo' => 'photo',
        'photos' => 'photos',
        'description' => 'description',
        'catalog_id' => 'catalog_id',
        'color1' => 'color1',
        'color2' => 'color2',
        'package_size_id' => 'package_size_id',
        'is_favourite' => 'is_favourite',
        'can_buy' => 'can_buy',
        'can_bundle' => 'can_bundle',
        'can_reserve' => 'can_reserve',
        'instant_buy' => 'instant_buy',
        'is_hidden' => 'is_hidden',
        'is_reserved' => 'is_reserved',
        'is_closed' => 'is_closed',
        'seller' => 'seller',
        'size_id' => 'size_id',
        'status_id' => 'status_id',
        'brand_id' => 'brand_id',
        'category' => 'category',
        'upload_date' => 'upload_date',
        'uploaded_at' => 'uploaded_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'title' => 'setTitle',
        'price' => 'setPrice',
        'brand_title' => 'setBrandTitle',
        'display_title' => 'setDisplayTitle',
        'display_subtitle' => 'setDisplaySubtitle',
        'size_title' => 'setSizeTitle',
        'status' => 'setStatus',
        'url' => 'setUrl',
        'path' => 'setPath',
        'is_visible' => 'setIsVisible',
        'promoted' => 'setPromoted',
        'favourite_count' => 'setFavouriteCount',
        'view_count' => 'setViewCount',
        'service_fee' => 'setServiceFee',
        'total_item_price' => 'setTotalItemPrice',
        'content_source' => 'setContentSource',
        'seller_country_code' => 'setSellerCountryCode',
        'similarity_score' => 'setSimilarityScore',
        'user' => 'setUser',
        'photo' => 'setPhoto',
        'photos' => 'setPhotos',
        'description' => 'setDescription',
        'catalog_id' => 'setCatalogId',
        'color1' => 'setColor1',
        'color2' => 'setColor2',
        'package_size_id' => 'setPackageSizeId',
        'is_favourite' => 'setIsFavourite',
        'can_buy' => 'setCanBuy',
        'can_bundle' => 'setCanBundle',
        'can_reserve' => 'setCanReserve',
        'instant_buy' => 'setInstantBuy',
        'is_hidden' => 'setIsHidden',
        'is_reserved' => 'setIsReserved',
        'is_closed' => 'setIsClosed',
        'seller' => 'setSeller',
        'size_id' => 'setSizeId',
        'status_id' => 'setStatusId',
        'brand_id' => 'setBrandId',
        'category' => 'setCategory',
        'upload_date' => 'setUploadDate',
        'uploaded_at' => 'setUploadedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'title' => 'getTitle',
        'price' => 'getPrice',
        'brand_title' => 'getBrandTitle',
        'display_title' => 'getDisplayTitle',
        'display_subtitle' => 'getDisplaySubtitle',
        'size_title' => 'getSizeTitle',
        'status' => 'getStatus',
        'url' => 'getUrl',
        'path' => 'getPath',
        'is_visible' => 'getIsVisible',
        'promoted' => 'getPromoted',
        'favourite_count' => 'getFavouriteCount',
        'view_count' => 'getViewCount',
        'service_fee' => 'getServiceFee',
        'total_item_price' => 'getTotalItemPrice',
        'content_source' => 'getContentSource',
        'seller_country_code' => 'getSellerCountryCode',
        'similarity_score' => 'getSimilarityScore',
        'user' => 'getUser',
        'photo' => 'getPhoto',
        'photos' => 'getPhotos',
        'description' => 'getDescription',
        'catalog_id' => 'getCatalogId',
        'color1' => 'getColor1',
        'color2' => 'getColor2',
        'package_size_id' => 'getPackageSizeId',
        'is_favourite' => 'getIsFavourite',
        'can_buy' => 'getCanBuy',
        'can_bundle' => 'getCanBundle',
        'can_reserve' => 'getCanReserve',
        'instant_buy' => 'getInstantBuy',
        'is_hidden' => 'getIsHidden',
        'is_reserved' => 'getIsReserved',
        'is_closed' => 'getIsClosed',
        'seller' => 'getSeller',
        'size_id' => 'getSizeId',
        'status_id' => 'getStatusId',
        'brand_id' => 'getBrandId',
        'category' => 'getCategory',
        'upload_date' => 'getUploadDate',
        'uploaded_at' => 'getUploadedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('brand_title', $data ?? [], null);
        $this->setIfExists('display_title', $data ?? [], null);
        $this->setIfExists('display_subtitle', $data ?? [], null);
        $this->setIfExists('size_title', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('is_visible', $data ?? [], true);
        $this->setIfExists('promoted', $data ?? [], false);
        $this->setIfExists('favourite_count', $data ?? [], 0);
        $this->setIfExists('view_count', $data ?? [], 0);
        $this->setIfExists('service_fee', $data ?? [], null);
        $this->setIfExists('total_item_price', $data ?? [], null);
        $this->setIfExists('content_source', $data ?? [], null);
        $this->setIfExists('seller_country_code', $data ?? [], null);
        $this->setIfExists('similarity_score', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('photo', $data ?? [], null);
        $this->setIfExists('photos', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('catalog_id', $data ?? [], null);
        $this->setIfExists('color1', $data ?? [], null);
        $this->setIfExists('color2', $data ?? [], null);
        $this->setIfExists('package_size_id', $data ?? [], null);
        $this->setIfExists('is_favourite', $data ?? [], false);
        $this->setIfExists('can_buy', $data ?? [], true);
        $this->setIfExists('can_bundle', $data ?? [], false);
        $this->setIfExists('can_reserve', $data ?? [], false);
        $this->setIfExists('instant_buy', $data ?? [], false);
        $this->setIfExists('is_hidden', $data ?? [], false);
        $this->setIfExists('is_reserved', $data ?? [], false);
        $this->setIfExists('is_closed', $data ?? [], false);
        $this->setIfExists('seller', $data ?? [], null);
        $this->setIfExists('size_id', $data ?? [], null);
        $this->setIfExists('status_id', $data ?? [], null);
        $this->setIfExists('brand_id', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('upload_date', $data ?? [], null);
        $this->setIfExists('uploaded_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \ScrapeBadger\Model\VintedPrice
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \ScrapeBadger\Model\VintedPrice $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets brand_title
     *
     * @return string|null
     */
    public function getBrandTitle()
    {
        return $this->container['brand_title'];
    }

    /**
     * Sets brand_title
     *
     * @param string|null $brand_title brand_title
     *
     * @return self
     */
    public function setBrandTitle($brand_title)
    {
        if (is_null($brand_title)) {
            array_push($this->openAPINullablesSetToNull, 'brand_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('brand_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['brand_title'] = $brand_title;

        return $this;
    }

    /**
     * Gets display_title
     *
     * @return string|null
     */
    public function getDisplayTitle()
    {
        return $this->container['display_title'];
    }

    /**
     * Sets display_title
     *
     * @param string|null $display_title display_title
     *
     * @return self
     */
    public function setDisplayTitle($display_title)
    {
        if (is_null($display_title)) {
            array_push($this->openAPINullablesSetToNull, 'display_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['display_title'] = $display_title;

        return $this;
    }

    /**
     * Gets display_subtitle
     *
     * @return string|null
     */
    public function getDisplaySubtitle()
    {
        return $this->container['display_subtitle'];
    }

    /**
     * Sets display_subtitle
     *
     * @param string|null $display_subtitle display_subtitle
     *
     * @return self
     */
    public function setDisplaySubtitle($display_subtitle)
    {
        if (is_null($display_subtitle)) {
            array_push($this->openAPINullablesSetToNull, 'display_subtitle');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_subtitle', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['display_subtitle'] = $display_subtitle;

        return $this;
    }

    /**
     * Gets size_title
     *
     * @return string|null
     */
    public function getSizeTitle()
    {
        return $this->container['size_title'];
    }

    /**
     * Sets size_title
     *
     * @param string|null $size_title size_title
     *
     * @return self
     */
    public function setSizeTitle($size_title)
    {
        if (is_null($size_title)) {
            array_push($this->openAPINullablesSetToNull, 'size_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('size_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['size_title'] = $size_title;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path path
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            array_push($this->openAPINullablesSetToNull, 'path');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('path', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets is_visible
     *
     * @return bool|null
     */
    public function getIsVisible()
    {
        return $this->container['is_visible'];
    }

    /**
     * Sets is_visible
     *
     * @param bool|null $is_visible is_visible
     *
     * @return self
     */
    public function setIsVisible($is_visible)
    {
        if (is_null($is_visible)) {
            throw new \InvalidArgumentException('non-nullable is_visible cannot be null');
        }
        $this->container['is_visible'] = $is_visible;

        return $this;
    }

    /**
     * Gets promoted
     *
     * @return bool|null
     */
    public function getPromoted()
    {
        return $this->container['promoted'];
    }

    /**
     * Sets promoted
     *
     * @param bool|null $promoted promoted
     *
     * @return self
     */
    public function setPromoted($promoted)
    {
        if (is_null($promoted)) {
            throw new \InvalidArgumentException('non-nullable promoted cannot be null');
        }
        $this->container['promoted'] = $promoted;

        return $this;
    }

    /**
     * Gets favourite_count
     *
     * @return int|null
     */
    public function getFavouriteCount()
    {
        return $this->container['favourite_count'];
    }

    /**
     * Sets favourite_count
     *
     * @param int|null $favourite_count favourite_count
     *
     * @return self
     */
    public function setFavouriteCount($favourite_count)
    {
        if (is_null($favourite_count)) {
            throw new \InvalidArgumentException('non-nullable favourite_count cannot be null');
        }
        $this->container['favourite_count'] = $favourite_count;

        return $this;
    }

    /**
     * Gets view_count
     *
     * @return int|null
     */
    public function getViewCount()
    {
        return $this->container['view_count'];
    }

    /**
     * Sets view_count
     *
     * @param int|null $view_count view_count
     *
     * @return self
     */
    public function setViewCount($view_count)
    {
        if (is_null($view_count)) {
            throw new \InvalidArgumentException('non-nullable view_count cannot be null');
        }
        $this->container['view_count'] = $view_count;

        return $this;
    }

    /**
     * Gets service_fee
     *
     * @return string|null
     */
    public function getServiceFee()
    {
        return $this->container['service_fee'];
    }

    /**
     * Sets service_fee
     *
     * @param string|null $service_fee service_fee
     *
     * @return self
     */
    public function setServiceFee($service_fee)
    {
        if (is_null($service_fee)) {
            array_push($this->openAPINullablesSetToNull, 'service_fee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_fee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_fee'] = $service_fee;

        return $this;
    }

    /**
     * Gets total_item_price
     *
     * @return string|null
     */
    public function getTotalItemPrice()
    {
        return $this->container['total_item_price'];
    }

    /**
     * Sets total_item_price
     *
     * @param string|null $total_item_price total_item_price
     *
     * @return self
     */
    public function setTotalItemPrice($total_item_price)
    {
        if (is_null($total_item_price)) {
            array_push($this->openAPINullablesSetToNull, 'total_item_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_item_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_item_price'] = $total_item_price;

        return $this;
    }

    /**
     * Gets content_source
     *
     * @return string|null
     */
    public function getContentSource()
    {
        return $this->container['content_source'];
    }

    /**
     * Sets content_source
     *
     * @param string|null $content_source content_source
     *
     * @return self
     */
    public function setContentSource($content_source)
    {
        if (is_null($content_source)) {
            array_push($this->openAPINullablesSetToNull, 'content_source');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('content_source', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['content_source'] = $content_source;

        return $this;
    }

    /**
     * Gets seller_country_code
     *
     * @return string|null
     */
    public function getSellerCountryCode()
    {
        return $this->container['seller_country_code'];
    }

    /**
     * Sets seller_country_code
     *
     * @param string|null $seller_country_code seller_country_code
     *
     * @return self
     */
    public function setSellerCountryCode($seller_country_code)
    {
        if (is_null($seller_country_code)) {
            array_push($this->openAPINullablesSetToNull, 'seller_country_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('seller_country_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['seller_country_code'] = $seller_country_code;

        return $this;
    }

    /**
     * Gets similarity_score
     *
     * @return float|null
     */
    public function getSimilarityScore()
    {
        return $this->container['similarity_score'];
    }

    /**
     * Sets similarity_score
     *
     * @param float|null $similarity_score similarity_score
     *
     * @return self
     */
    public function setSimilarityScore($similarity_score)
    {
        if (is_null($similarity_score)) {
            array_push($this->openAPINullablesSetToNull, 'similarity_score');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('similarity_score', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['similarity_score'] = $similarity_score;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \ScrapeBadger\Model\VintedUserSummary|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \ScrapeBadger\Model\VintedUserSummary|null $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            array_push($this->openAPINullablesSetToNull, 'user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets photo
     *
     * @return \ScrapeBadger\Model\VintedPhoto|null
     */
    public function getPhoto()
    {
        return $this->container['photo'];
    }

    /**
     * Sets photo
     *
     * @param \ScrapeBadger\Model\VintedPhoto|null $photo photo
     *
     * @return self
     */
    public function setPhoto($photo)
    {
        if (is_null($photo)) {
            array_push($this->openAPINullablesSetToNull, 'photo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('photo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['photo'] = $photo;

        return $this;
    }

    /**
     * Gets photos
     *
     * @return \ScrapeBadger\Model\VintedPhoto[]|null
     */
    public function getPhotos()
    {
        return $this->container['photos'];
    }

    /**
     * Sets photos
     *
     * @param \ScrapeBadger\Model\VintedPhoto[]|null $photos photos
     *
     * @return self
     */
    public function setPhotos($photos)
    {
        if (is_null($photos)) {
            throw new \InvalidArgumentException('non-nullable photos cannot be null');
        }
        $this->container['photos'] = $photos;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets catalog_id
     *
     * @return int|null
     */
    public function getCatalogId()
    {
        return $this->container['catalog_id'];
    }

    /**
     * Sets catalog_id
     *
     * @param int|null $catalog_id catalog_id
     *
     * @return self
     */
    public function setCatalogId($catalog_id)
    {
        if (is_null($catalog_id)) {
            array_push($this->openAPINullablesSetToNull, 'catalog_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('catalog_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['catalog_id'] = $catalog_id;

        return $this;
    }

    /**
     * Gets color1
     *
     * @return string|null
     */
    public function getColor1()
    {
        return $this->container['color1'];
    }

    /**
     * Sets color1
     *
     * @param string|null $color1 color1
     *
     * @return self
     */
    public function setColor1($color1)
    {
        if (is_null($color1)) {
            array_push($this->openAPINullablesSetToNull, 'color1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['color1'] = $color1;

        return $this;
    }

    /**
     * Gets color2
     *
     * @return string|null
     */
    public function getColor2()
    {
        return $this->container['color2'];
    }

    /**
     * Sets color2
     *
     * @param string|null $color2 color2
     *
     * @return self
     */
    public function setColor2($color2)
    {
        if (is_null($color2)) {
            array_push($this->openAPINullablesSetToNull, 'color2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['color2'] = $color2;

        return $this;
    }

    /**
     * Gets package_size_id
     *
     * @return int|null
     */
    public function getPackageSizeId()
    {
        return $this->container['package_size_id'];
    }

    /**
     * Sets package_size_id
     *
     * @param int|null $package_size_id package_size_id
     *
     * @return self
     */
    public function setPackageSizeId($package_size_id)
    {
        if (is_null($package_size_id)) {
            array_push($this->openAPINullablesSetToNull, 'package_size_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('package_size_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['package_size_id'] = $package_size_id;

        return $this;
    }

    /**
     * Gets is_favourite
     *
     * @return bool|null
     */
    public function getIsFavourite()
    {
        return $this->container['is_favourite'];
    }

    /**
     * Sets is_favourite
     *
     * @param bool|null $is_favourite is_favourite
     *
     * @return self
     */
    public function setIsFavourite($is_favourite)
    {
        if (is_null($is_favourite)) {
            throw new \InvalidArgumentException('non-nullable is_favourite cannot be null');
        }
        $this->container['is_favourite'] = $is_favourite;

        return $this;
    }

    /**
     * Gets can_buy
     *
     * @return bool|null
     */
    public function getCanBuy()
    {
        return $this->container['can_buy'];
    }

    /**
     * Sets can_buy
     *
     * @param bool|null $can_buy can_buy
     *
     * @return self
     */
    public function setCanBuy($can_buy)
    {
        if (is_null($can_buy)) {
            throw new \InvalidArgumentException('non-nullable can_buy cannot be null');
        }
        $this->container['can_buy'] = $can_buy;

        return $this;
    }

    /**
     * Gets can_bundle
     *
     * @return bool|null
     */
    public function getCanBundle()
    {
        return $this->container['can_bundle'];
    }

    /**
     * Sets can_bundle
     *
     * @param bool|null $can_bundle can_bundle
     *
     * @return self
     */
    public function setCanBundle($can_bundle)
    {
        if (is_null($can_bundle)) {
            throw new \InvalidArgumentException('non-nullable can_bundle cannot be null');
        }
        $this->container['can_bundle'] = $can_bundle;

        return $this;
    }

    /**
     * Gets can_reserve
     *
     * @return bool|null
     */
    public function getCanReserve()
    {
        return $this->container['can_reserve'];
    }

    /**
     * Sets can_reserve
     *
     * @param bool|null $can_reserve can_reserve
     *
     * @return self
     */
    public function setCanReserve($can_reserve)
    {
        if (is_null($can_reserve)) {
            throw new \InvalidArgumentException('non-nullable can_reserve cannot be null');
        }
        $this->container['can_reserve'] = $can_reserve;

        return $this;
    }

    /**
     * Gets instant_buy
     *
     * @return bool|null
     */
    public function getInstantBuy()
    {
        return $this->container['instant_buy'];
    }

    /**
     * Sets instant_buy
     *
     * @param bool|null $instant_buy instant_buy
     *
     * @return self
     */
    public function setInstantBuy($instant_buy)
    {
        if (is_null($instant_buy)) {
            throw new \InvalidArgumentException('non-nullable instant_buy cannot be null');
        }
        $this->container['instant_buy'] = $instant_buy;

        return $this;
    }

    /**
     * Gets is_hidden
     *
     * @return bool|null
     */
    public function getIsHidden()
    {
        return $this->container['is_hidden'];
    }

    /**
     * Sets is_hidden
     *
     * @param bool|null $is_hidden is_hidden
     *
     * @return self
     */
    public function setIsHidden($is_hidden)
    {
        if (is_null($is_hidden)) {
            throw new \InvalidArgumentException('non-nullable is_hidden cannot be null');
        }
        $this->container['is_hidden'] = $is_hidden;

        return $this;
    }

    /**
     * Gets is_reserved
     *
     * @return bool|null
     */
    public function getIsReserved()
    {
        return $this->container['is_reserved'];
    }

    /**
     * Sets is_reserved
     *
     * @param bool|null $is_reserved is_reserved
     *
     * @return self
     */
    public function setIsReserved($is_reserved)
    {
        if (is_null($is_reserved)) {
            throw new \InvalidArgumentException('non-nullable is_reserved cannot be null');
        }
        $this->container['is_reserved'] = $is_reserved;

        return $this;
    }

    /**
     * Gets is_closed
     *
     * @return bool|null
     */
    public function getIsClosed()
    {
        return $this->container['is_closed'];
    }

    /**
     * Sets is_closed
     *
     * @param bool|null $is_closed is_closed
     *
     * @return self
     */
    public function setIsClosed($is_closed)
    {
        if (is_null($is_closed)) {
            throw new \InvalidArgumentException('non-nullable is_closed cannot be null');
        }
        $this->container['is_closed'] = $is_closed;

        return $this;
    }

    /**
     * Gets seller
     *
     * @return \ScrapeBadger\Model\VintedSellerSummary|null
     */
    public function getSeller()
    {
        return $this->container['seller'];
    }

    /**
     * Sets seller
     *
     * @param \ScrapeBadger\Model\VintedSellerSummary|null $seller seller
     *
     * @return self
     */
    public function setSeller($seller)
    {
        if (is_null($seller)) {
            array_push($this->openAPINullablesSetToNull, 'seller');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('seller', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['seller'] = $seller;

        return $this;
    }

    /**
     * Gets size_id
     *
     * @return int|null
     */
    public function getSizeId()
    {
        return $this->container['size_id'];
    }

    /**
     * Sets size_id
     *
     * @param int|null $size_id size_id
     *
     * @return self
     */
    public function setSizeId($size_id)
    {
        if (is_null($size_id)) {
            array_push($this->openAPINullablesSetToNull, 'size_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('size_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['size_id'] = $size_id;

        return $this;
    }

    /**
     * Gets status_id
     *
     * @return int|null
     */
    public function getStatusId()
    {
        return $this->container['status_id'];
    }

    /**
     * Sets status_id
     *
     * @param int|null $status_id status_id
     *
     * @return self
     */
    public function setStatusId($status_id)
    {
        if (is_null($status_id)) {
            array_push($this->openAPINullablesSetToNull, 'status_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status_id'] = $status_id;

        return $this;
    }

    /**
     * Gets brand_id
     *
     * @return int|null
     */
    public function getBrandId()
    {
        return $this->container['brand_id'];
    }

    /**
     * Sets brand_id
     *
     * @param int|null $brand_id brand_id
     *
     * @return self
     */
    public function setBrandId($brand_id)
    {
        if (is_null($brand_id)) {
            array_push($this->openAPINullablesSetToNull, 'brand_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('brand_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['brand_id'] = $brand_id;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string[]|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string[]|null $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            throw new \InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets upload_date
     *
     * @return string|null
     */
    public function getUploadDate()
    {
        return $this->container['upload_date'];
    }

    /**
     * Sets upload_date
     *
     * @param string|null $upload_date upload_date
     *
     * @return self
     */
    public function setUploadDate($upload_date)
    {
        if (is_null($upload_date)) {
            array_push($this->openAPINullablesSetToNull, 'upload_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('upload_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['upload_date'] = $upload_date;

        return $this;
    }

    /**
     * Gets uploaded_at
     *
     * @return string|null
     */
    public function getUploadedAt()
    {
        return $this->container['uploaded_at'];
    }

    /**
     * Sets uploaded_at
     *
     * @param string|null $uploaded_at uploaded_at
     *
     * @return self
     */
    public function setUploadedAt($uploaded_at)
    {
        if (is_null($uploaded_at)) {
            array_push($this->openAPINullablesSetToNull, 'uploaded_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('uploaded_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['uploaded_at'] = $uploaded_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


