<?php
/**
 * FilterRuleDeliveryLogResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ScrapeBadger\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FilterRuleDeliveryLogResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Delivery log entry for a filter rule.
 * @package     ScrapeBadger
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FilterRuleDeliveryLogResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FilterRuleDeliveryLogResponse"
     */
    public function testFilterRuleDeliveryLogResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rule_id"
     */
    public function testPropertyRuleId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rule_tag"
     */
    public function testPropertyRuleTag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tweet_id"
     */
    public function testPropertyTweetId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "author_username"
     */
    public function testPropertyAuthorUsername()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tweet_text_preview"
     */
    public function testPropertyTweetTextPreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tweet_url"
     */
    public function testPropertyTweetUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tweet_published_at"
     */
    public function testPropertyTweetPublishedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "detected_at"
     */
    public function testPropertyDetectedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "latency_ms"
     */
    public function testPropertyLatencyMs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "latency_badge"
     */
    public function testPropertyLatencyBadge()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery_status"
     */
    public function testPropertyDeliveryStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "webhook_status_code"
     */
    public function testPropertyWebhookStatusCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "webhook_attempts"
     */
    public function testPropertyWebhookAttempts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
