<?php
/**
 * DuckDuckGoApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DuckDuckGoApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DuckDuckGoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for duckduckgoDuckduckgoScraperHealthCheck
     *
     * DuckDuckGo scraper health check.
     *
     */
    public function testDuckduckgoDuckduckgoScraperHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoDuckduckgoScraperHealthCheckHead
     *
     * DuckDuckGo scraper health check.
     *
     */
    public function testDuckduckgoDuckduckgoScraperHealthCheckHead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoImageSearch
     *
     * Image search.
     *
     */
    public function testDuckduckgoImageSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoInstantAnswer
     *
     * Instant Answer.
     *
     */
    public function testDuckduckgoInstantAnswer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoListSupportedRegions
     *
     * List supported regions.
     *
     */
    public function testDuckduckgoListSupportedRegions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoNewsSearch
     *
     * News search.
     *
     */
    public function testDuckduckgoNewsSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoSearchSuggestions
     *
     * Search suggestions.
     *
     */
    public function testDuckduckgoSearchSuggestions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoVideoSearch
     *
     * Video search.
     *
     */
    public function testDuckduckgoVideoSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for duckduckgoWebSearch
     *
     * Web search.
     *
     */
    public function testDuckduckgoWebSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
