<?php
/**
 * FacebookApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FacebookApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FacebookApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for facebookBrowseAMarketplaceCategory
     *
     * Browse a Marketplace category.
     *
     */
    public function testFacebookBrowseAMarketplaceCategory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetAMarketplaceItem
     *
     * Get a Marketplace item.
     *
     */
    public function testFacebookGetAMarketplaceItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetAdvertiserPageInfo
     *
     * Get advertiser page info.
     *
     */
    public function testFacebookGetAdvertiserPageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetAnAd
     *
     * Get an ad.
     *
     */
    public function testFacebookGetAnAd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetGroupDetail
     *
     * Get group detail.
     *
     */
    public function testFacebookGetGroupDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetGroupPosts
     *
     * Get group posts.
     *
     */
    public function testFacebookGetGroupPosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetPageDetail
     *
     * Get page detail.
     *
     */
    public function testFacebookGetPageDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetPagePosts
     *
     * Get page posts.
     *
     */
    public function testFacebookGetPagePosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetPostComments
     *
     * Get post comments.
     *
     */
    public function testFacebookGetPostComments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetPostDetail
     *
     * Get post detail.
     *
     */
    public function testFacebookGetPostDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetProfileDetail
     *
     * Get profile detail.
     *
     */
    public function testFacebookGetProfileDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookGetProfilePosts
     *
     * Get profile posts.
     *
     */
    public function testFacebookGetProfilePosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookListCategories
     *
     * List categories.
     *
     */
    public function testFacebookListCategories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookListLocations
     *
     * List locations.
     *
     */
    public function testFacebookListLocations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchAdvertiserPages
     *
     * Search advertiser pages.
     *
     */
    public function testFacebookSearchAdvertiserPages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchEvents
     *
     * Search events.
     *
     */
    public function testFacebookSearchEvents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchEverything
     *
     * Search everything.
     *
     */
    public function testFacebookSearchEverything()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchGroups
     *
     * Search groups.
     *
     */
    public function testFacebookSearchGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchMarketplace
     *
     * Search Marketplace.
     *
     */
    public function testFacebookSearchMarketplace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchPages
     *
     * Search Pages.
     *
     */
    public function testFacebookSearchPages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchPeople
     *
     * Search people.
     *
     */
    public function testFacebookSearchPeople()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchPlaces
     *
     * Search places.
     *
     */
    public function testFacebookSearchPlaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchPosts
     *
     * Search posts.
     *
     */
    public function testFacebookSearchPosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for facebookSearchTheAdLibrary
     *
     * Search the Ad Library.
     *
     */
    public function testFacebookSearchTheAdLibrary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
