<?php
/**
 * GooglePlayApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GooglePlayApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GooglePlayApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for googlePlayBrowseACategory
     *
     * Browse a category.
     *
     */
    public function testGooglePlayBrowseACategory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayGetAppDetail
     *
     * Get app detail.
     *
     */
    public function testGooglePlayGetAppDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayGetAppPermissions
     *
     * Get app permissions.
     *
     */
    public function testGooglePlayGetAppPermissions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayGetAppReviews
     *
     * Get app reviews.
     *
     */
    public function testGooglePlayGetAppReviews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayGetDeveloperApps
     *
     * Get developer apps.
     *
     */
    public function testGooglePlayGetDeveloperApps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayGetSimilarApps
     *
     * Get similar apps.
     *
     */
    public function testGooglePlayGetSimilarApps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayListCategories
     *
     * List categories.
     *
     */
    public function testGooglePlayListCategories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayListMarkets
     *
     * List markets.
     *
     */
    public function testGooglePlayListMarkets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlaySearchApps
     *
     * Search apps.
     *
     */
    public function testGooglePlaySearchApps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for googlePlayTopCharts
     *
     * Top charts.
     *
     */
    public function testGooglePlayTopCharts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
