<?php
/**
 * ImmobiliareApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ImmobiliareApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImmobiliareApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for immobiliareGetAgencyProfile
     *
     * Get agency profile.
     *
     */
    public function testImmobiliareGetAgencyProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareGetAnAgencySListings
     *
     * Get an agency's listings.
     *
     */
    public function testImmobiliareGetAnAgencySListings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareGetListingDetail
     *
     * Get listing detail.
     *
     */
    public function testImmobiliareGetListingDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareImmobiliareScraperHealthCheck
     *
     * Immobiliare scraper health check.
     *
     */
    public function testImmobiliareImmobiliareScraperHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareImmobiliareScraperHealthCheckHead
     *
     * Immobiliare scraper health check.
     *
     */
    public function testImmobiliareImmobiliareScraperHealthCheckHead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareListFilterEnums
     *
     * List filter enums.
     *
     */
    public function testImmobiliareListFilterEnums()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareListMarkets
     *
     * List markets.
     *
     */
    public function testImmobiliareListMarkets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareLocationAutocomplete
     *
     * Location autocomplete.
     *
     */
    public function testImmobiliareLocationAutocomplete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliarePriceMTimeSeries
     *
     * Price €/m² time series.
     *
     */
    public function testImmobiliarePriceMTimeSeries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for immobiliareSearchListings
     *
     * Search listings.
     *
     */
    public function testImmobiliareSearchListings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
