<?php
/**
 * LinkedInApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LinkedInApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LinkedInApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for linkedinGetACompanySJobPostings
     *
     * Get a company's job postings.
     *
     */
    public function testLinkedinGetACompanySJobPostings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinGetACourse
     *
     * Get a course.
     *
     */
    public function testLinkedinGetACourse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinGetAPublicArticle
     *
     * Get a public article.
     *
     */
    public function testLinkedinGetAPublicArticle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinGetAPublicPost
     *
     * Get a public post.
     *
     */
    public function testLinkedinGetAPublicPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinGetCompany
     *
     * Get company.
     *
     */
    public function testLinkedinGetCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinGetJobDetail
     *
     * Get job detail.
     *
     */
    public function testLinkedinGetJobDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinGetPublicProfile
     *
     * Get public profile.
     *
     */
    public function testLinkedinGetPublicProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinGetSchool
     *
     * Get school.
     *
     */
    public function testLinkedinGetSchool()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinLinkedinScraperHealthCheck
     *
     * LinkedIn scraper health check.
     *
     */
    public function testLinkedinLinkedinScraperHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinLinkedinScraperHealthCheckHead
     *
     * LinkedIn scraper health check.
     *
     */
    public function testLinkedinLinkedinScraperHealthCheckHead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinSearchLinkedinJobs
     *
     * Search LinkedIn jobs.
     *
     */
    public function testLinkedinSearchLinkedinJobs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkedinSuggestLocationGeoIds
     *
     * Suggest location geo ids.
     *
     */
    public function testLinkedinSuggestLocationGeoIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
