<?php
/**
 * PerplexityApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PerplexityApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PerplexityApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for perplexityAskPerplexityAQuestion
     *
     * Ask Perplexity a question.
     *
     */
    public function testPerplexityAskPerplexityAQuestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for perplexityAskPerplexityAQuestionPost
     *
     * Ask Perplexity a question (POST).
     *
     */
    public function testPerplexityAskPerplexityAQuestionPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for perplexityMeasureABrandSVisibilityInAPerplexityAnswer
     *
     * Measure a brand's visibility in a Perplexity answer.
     *
     */
    public function testPerplexityMeasureABrandSVisibilityInAPerplexityAnswer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost
     *
     * Measure a brand's visibility in a Perplexity answer (POST).
     *
     */
    public function testPerplexityMeasureABrandSVisibilityInAPerplexityAnswerPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for perplexityPerplexityScraperHealthCheck
     *
     * Perplexity scraper health check.
     *
     */
    public function testPerplexityPerplexityScraperHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for perplexityPerplexityScraperHealthCheckHead
     *
     * Perplexity scraper health check.
     *
     */
    public function testPerplexityPerplexityScraperHealthCheckHead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
