<?php
/**
 * RealtorApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RealtorApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RealtorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for realtorGetFullPropertyDetail
     *
     * Get full property detail.
     *
     */
    public function testRealtorGetFullPropertyDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for realtorListMarkets
     *
     * List markets.
     *
     */
    public function testRealtorListMarkets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for realtorLocationAutocomplete
     *
     * Location autocomplete.
     *
     */
    public function testRealtorLocationAutocomplete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for realtorRealtorScraperHealthCheck
     *
     * Realtor scraper health check.
     *
     */
    public function testRealtorRealtorScraperHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for realtorRealtorScraperHealthCheckHead
     *
     * Realtor scraper health check.
     *
     */
    public function testRealtorRealtorScraperHealthCheckHead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for realtorSearchPropertyListings
     *
     * Search property listings.
     *
     */
    public function testRealtorSearchPropertyListings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
