<?php
/**
 * RedfinApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RedfinApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RedfinApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for redfinGetAgentProfileListings
     *
     * Get agent profile + listings.
     *
     */
    public function testRedfinGetAgentProfileListings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redfinGetPropertyDetail
     *
     * Get property detail.
     *
     */
    public function testRedfinGetPropertyDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redfinGetPropertyDetailByUrl
     *
     * Get property detail by URL.
     *
     */
    public function testRedfinGetPropertyDetailByUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redfinListCoverageMarkets
     *
     * List coverage markets.
     *
     */
    public function testRedfinListCoverageMarkets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redfinRedfinScraperHealthCheck
     *
     * Redfin scraper health check.
     *
     */
    public function testRedfinRedfinScraperHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redfinRedfinScraperHealthCheckHead
     *
     * Redfin scraper health check.
     *
     */
    public function testRedfinRedfinScraperHealthCheckHead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redfinRegionAddressSuggestions
     *
     * Region/address suggestions.
     *
     */
    public function testRedfinRegionAddressSuggestions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redfinSearchProperties
     *
     * Search properties.
     *
     */
    public function testRedfinSearchProperties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
