<?php
/**
 * YandexApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ScrapeBadger\Test\Api;

use \ScrapeBadger\Configuration;
use \ScrapeBadger\ApiException;
use \ScrapeBadger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * YandexApiTest Class Doc Comment
 *
 * @category Class
 * @package  ScrapeBadger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class YandexApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for yandexImageSearch
     *
     * Image search.
     *
     */
    public function testYandexImageSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for yandexListSupportedMarkets
     *
     * List supported markets.
     *
     */
    public function testYandexListSupportedMarkets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for yandexReverseImageSearch
     *
     * Reverse image search.
     *
     */
    public function testYandexReverseImageSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for yandexWebSearch
     *
     * Web search.
     *
     */
    public function testYandexWebSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for yandexYandexScraperHealthCheck
     *
     * Yandex scraper health check.
     *
     */
    public function testYandexYandexScraperHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for yandexYandexScraperHealthCheckHead
     *
     * Yandex scraper health check.
     *
     */
    public function testYandexYandexScraperHealthCheckHead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
